export enum EduDegreeEnum {
  BACHELOR = 'BACHELOR',
  MASTERS_DEGREE  = 'MASTERS_DEGREE',
  LANGUAGE_PROGRAM = 'LANGUAGE_PROGRAM',
  FOUNDATION = 'FOUNDATION',
  DEGREE_PREPARATION = 'DEGREE_PREPARATION',
}
