version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: nova_postgres
    ports:
      - 4682:5432
    environment:
      POSTGRES_DB: '${DB_NAME}'
      DB_NAME: '${DB_NAME}'
      DB_SCHEMA: '${DB_SCHEMA}'
      DB_APP_USER: '${DB_APP_USER}'
      DB_APP_PASS: '${DB_APP_PASS}'
      DB_MIGRATOR_USER: '${DB_MIGRATOR_USER}'
      DB_MIGRATOR_PASS: '${DB_MIGRATOR_PASS}'
      POSTGRES_PASSWORD: '${DB_MIGRATOR_PASS}'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - $EXTERNAL_PATH/files:$FILE_PATH
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - default

networks:
  default:
