export enum ApplicationStatusEnum {
  DRAFT = 'DRAFT',
  APPLICATION_RECEIVED = 'APPLICATION_RECEIVED',
  UNDER_CONSIDERATION = 'UNDER_CONSIDERATION',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  CONFIRMED = 'CONFIRMED',
  DEPARTURE = 'DEPARTURE',
}
